'use client';

import { useState } from 'react';
import { Dialog } from './ui/Dialog';
import { Input } from './ui/Input';
import { Button } from './ui/Button';
import { useSettings } from '@/lib/settings';
import { normalizeApiKey, isPlausibleApiKey } from '@/lib/gemini/keys';

type Props = {
  readonly open: boolean;
  readonly onClose: () => void;
  /** Runs after a successful save, so Generate can proceed with the action the
   *  user originally asked for rather than making them tap twice. */
  readonly onSaved?: () => void;
};

/**
 * Key entry.
 *
 * The leading two sentences are disclosure, not onboarding: without them the
 * app's only real feature fails silently for every new visitor. No tour, no
 * modal on first load, no marketing copy.
 *
 * The sessionStorage warning is required — the key dies with the tab, and
 * without saying so users re-paste every session and conclude it is broken.
 */
export function ApiKeyDialog({ open, onClose, onSaved }: Props) {
  const apiKey = useSettings((s) => s.apiKey);
  const setApiKey = useSettings((s) => s.setApiKey);
  const [value, setValue] = useState('');
  const [error, setError] = useState<string | null>(null);

  const save = () => {
    const trimmed = normalizeApiKey(value);
    if (!isPlausibleApiKey(trimmed)) {
      setError('That does not look like a Gemini API key.');
      return;
    }
    setApiKey(trimmed);
    setValue('');
    setError(null);
    onClose();
    onSaved?.();
  };

  return (
    <Dialog open={open} onClose={onClose} title="Gemini API key">
      <p className="text-[13px] leading-[1.5] text-[var(--color-text)]">
        Questions are generated by Google&rsquo;s Gemini API using your own key, so generation runs
        on your quota and costs this site nothing.
      </p>
      <p className="mt-2 text-[13px] leading-[1.5] text-[var(--color-text-muted)]">
        Create a{' '}
        <a
          href="https://aistudio.google.com/app/apikey"
          target="_blank"
          rel="noreferrer noopener"
          className="text-[var(--color-accent)] underline underline-offset-2"
        >
          key at aistudio.google.com
        </a>
        . Make a dedicated one you can revoke, rather than reusing a key you rely on elsewhere.
      </p>

      <div className="mt-4">
        <Input
          type="password"
          inputMode="text"
          autoComplete="off"
          spellCheck={false}
          placeholder={apiKey ? 'Replace stored key' : 'Paste your API key'}
          value={value}
          onChange={(e) => {
            setValue(e.target.value);
            setError(null);
          }}
          onKeyDown={(e) => e.key === 'Enter' && save()}
          aria-label="Gemini API key"
        />
        {error && <p className="mt-1.5 text-[12px] text-[var(--color-incorrect)]">{error}</p>}
      </div>

      <p className="mt-2 text-[12px] leading-[1.45] text-[var(--color-text-muted)]">
        Cleared when you close this tab. Sign in to save it.
      </p>

      <div className="mt-4 flex gap-2">
        <Button variant="primary" className="flex-1" onClick={save}>
          Save key
        </Button>
        {apiKey && (
          <Button
            variant="secondary"
            onClick={() => {
              setApiKey(null);
              onClose();
            }}
          >
            Remove
          </Button>
        )}
      </div>
    </Dialog>
  );
}
